{{- $fullName := include "protein-design-chart.fullname" . -}}
{{- $labels := include "protein-design-chart.labels" . -}}
{{- $selectorLabels := include "protein-design-chart.selectorLabels" . -}}

{{- $services := list "alphafold2" "rfdiffusion" "proteinmpnn" "alphafold2multimer" -}}

{{- range $serviceName := $services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $serviceName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ index $.Values $serviceName "servicePort" }}
      targetPort: {{ index $.Values $serviceName "containerPort" }}
      protocol: TCP
      name: "{{ $serviceName }}-port"
  selector:
    {{- $selectorLabels | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}