name: protein-binder-design

services:
  ## AlphaFold2
  ## AlphaFold2 is pinned to GPU 0
  alphafold:
    image: nvcr.io/nim/deepmind/alphafold2:2.1
    pull_policy: always
    runtime: nvidia
    ports:
      - "8081:8000"
    volumes:
      - ${HOST_NIM_CACHE:-~/.cache/nim}:/opt/nim/.cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [gpu]
              device_ids: ['0']
    environment:
      - NGC_API_KEY=${NGC_CLI_API_KEY:?Error NGC_CLI_API_KEY not set}
      - NIM_CACHE_PATH=/opt/nim/.cache
      - NIM_DISABLE_MODEL_DOWNLOAD=False ## Set this to True to disable model download.
      - CUDA_VISIBLE_DEVICES=0


  ## RFDiffusion
  ## RFDiffusion is pinned to GPU 1.
  rfdiffusion:
    image: nvcr.io/nim/ipd/rfdiffusion:2.0
    pull_policy: always
    runtime: nvidia
    ports:
      - "8082:8000"
    volumes:
      - ${HOST_NIM_CACHE:-~/.cache/nim}:/home/nvs/.cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [gpu]
              device_ids: ['1']
    environment:
      - NGC_CLI_API_KEY=${NGC_CLI_API_KEY:?Error NGC_CLI_API_KEY not set}
      - NIM_CACHE_PATH=/home/nvs/.cache/nim/models


  proteinmpnn:
    image: nvcr.io/nim/ipd/proteinmpnn:1.0
    pull_policy: always
    runtime: nvidia
    ports:
      - "8083:8000"
    volumes:
      - ${HOST_NIM_CACHE:-~/.cache/nim}:/home/nvs/.cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [gpu]
              device_ids: ['2']
    environment:
      - NGC_CLI_API_KEY=${NGC_CLI_API_KEY:?Error NGC_CLI_API_KEY not set}
      - NIM_CACHE_PATH=/home/nvs/.cache/nim/models

  alphafold-multimer:
    image: nvcr.io/nim/deepmind/alphafold2-multimer:2.1
    pull_policy: always
    runtime: nvidia
    ports:
      - "8084:8000"
    volumes:
      - ${HOST_NIM_CACHE:-~/.cache/nim}:/opt/nim/.cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [gpu]
              device_ids: ['3']
    environment:
      - NGC_API_KEY=${NGC_CLI_API_KEY:?Error NGC_CLI_API_KEY not set}
      - NIM_CACHE_PATH=/opt/nim/.cache/
      - NIM_DISABLE_MODEL_DOWNLOAD=False
      - CUDA_VISIBILE_DEVICES=3
